"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

interface OnboardingFormProps {
  playerId: string;
  initialDisplayName: string;
  initialDupr: number | null;
}

export default function OnboardingForm({
  playerId,
  initialDisplayName,
  initialDupr,
}: OnboardingFormProps) {
  const router = useRouter();

  // Default the display name to empty if it looks auto-generated from email
  // (lowercase, no spaces) — encourage user to set a real name.
  const looksAutoGenerated =
    /^[a-z0-9._-]+$/.test(initialDisplayName) &&
    !initialDisplayName.includes(" ");
  const [displayName, setDisplayName] = useState(
    looksAutoGenerated ? "" : initialDisplayName,
  );
  const [dupr, setDupr] = useState<number>(initialDupr ?? 3.0);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!displayName.trim()) {
      setError("Please enter your name.");
      return;
    }
    setSaving(true);
    setError(null);

    const supabase = createClient();
    const { error } = await supabase
      .from("players")
      .update({
        display_name: displayName.trim(),
        dupr_self_rating: dupr,
        onboarding_completed_at: new Date().toISOString(),
      })
      .eq("id", playerId);

    if (error) {
      setError(error.message);
      setSaving(false);
      return;
    }

    router.push("/");
    router.refresh();
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <label className="block">
        <span className="font-display text-display-xs uppercase font-semibold tracking-wide text-pickle">
          Your name
        </span>
        <input
          type="text"
          value={displayName}
          onChange={(e) => setDisplayName(e.target.value)}
          required
          maxLength={40}
          autoFocus
          placeholder="First name or nickname"
          className="mt-2 block w-full rounded-lg border-2 border-white bg-black px-4 py-3 text-base text-white placeholder:text-white/40 focus:border-pickle focus:outline-none"
        />
        <p className="mt-1.5 text-xs text-white/40">
          Shown next to your matches. You can change it any time.
        </p>
      </label>

      <label className="block">
        <span className="font-display text-display-xs uppercase font-semibold tracking-wide text-pickle">
          Self-rating ({dupr.toFixed(1)})
        </span>
        <input
          type="range"
          min={2.0}
          max={8.0}
          step={0.5}
          value={dupr}
          onChange={(e) => setDupr(parseFloat(e.target.value))}
          className="mt-2 w-full accent-pickle"
        />
        <div className="mt-1 flex justify-between font-mono text-xs text-white/40">
          <span>2.0</span>
          <span>5.0</span>
          <span>8.0</span>
        </div>
        <p className="mt-2 text-xs text-white/50 leading-relaxed">
          DUPR-style: 2.0 = beginner, 3.0–4.0 = intermediate, 4.0–5.0 = advanced,
          5.0+ = elite. You can adjust later.
        </p>
      </label>

      <div className="flex items-center gap-3 pt-2">
        <button
          type="submit"
          disabled={saving}
          className="soft-stamp w-full rounded-xl bg-pickle px-6 py-4 font-display text-display-base font-extrabold uppercase tracking-wide text-black disabled:opacity-50"
        >
          {saving ? "Saving..." : "Let's play"}
        </button>
      </div>

      {error && (
        <p className="text-base text-bright">⚠ {error}</p>
      )}
    </form>
  );
}
