"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

interface WelcomeFlowProps {
  playerId: string;
  initialDisplayName: string;
  initialDupr: number | null;
}

const TOTAL_STEPS = 4;

export default function WelcomeFlow({
  playerId,
  initialDisplayName,
  initialDupr,
}: WelcomeFlowProps) {
  const router = useRouter();

  const [step, setStep] = useState(0);

  // Form state (used on step 3)
  const looksAutoGenerated =
    /^[a-z0-9._-]+$/.test(initialDisplayName) &&
    !initialDisplayName.includes(" ");
  const [displayName, setDisplayName] = useState(
    looksAutoGenerated ? "" : initialDisplayName,
  );
  const [dupr, setDupr] = useState<number>(initialDupr ?? 3.0);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleFinish() {
    if (!displayName.trim()) {
      setError("Please enter your name.");
      return;
    }
    setSaving(true);
    setError(null);

    const supabase = createClient();
    const { error } = await supabase
      .from("players")
      .update({
        display_name: displayName.trim(),
        dupr_self_rating: dupr,
        onboarding_completed_at: new Date().toISOString(),
      })
      .eq("id", playerId);

    if (error) {
      setError(error.message);
      setSaving(false);
      return;
    }
    router.push("/");
    router.refresh();
  }

  return (
    <div className="space-y-6">
      {/* Step indicator */}
      <div className="flex items-center justify-between">
        <span className="font-display text-display-xs uppercase font-semibold tracking-wide text-pickle">
          Step {step + 1} / {TOTAL_STEPS}
        </span>
        <div className="flex items-center gap-1.5">
          {Array.from({ length: TOTAL_STEPS }).map((_, i) => (
            <span
              key={i}
              className={`h-1.5 w-6 rounded-full transition ${
                i <= step ? "bg-pickle" : "bg-white/15"
              }`}
            />
          ))}
        </div>
      </div>

      {step === 0 && <IntroSlide onNext={() => setStep(1)} />}
      {step === 1 && (
        <VouchSlide onBack={() => setStep(0)} onNext={() => setStep(2)} />
      )}
      {step === 2 && (
        <CompeteSlide onBack={() => setStep(1)} onNext={() => setStep(3)} />
      )}
      {step === 3 && (
        <FormStep
          displayName={displayName}
          setDisplayName={setDisplayName}
          dupr={dupr}
          setDupr={setDupr}
          saving={saving}
          error={error}
          onBack={() => setStep(2)}
          onSubmit={handleFinish}
        />
      )}
    </div>
  );
}

// ----- slide components -----

function IntroSlide({ onNext }: { onNext: () => void }) {
  return (
    <div className="space-y-4">
      <h2 className="font-display text-display-2xl font-extrabold leading-tight text-bright">
        Welcome to PKLRALLY
      </h2>
      <p className="text-base text-white/80 leading-relaxed">
        The live pulse of pickleball. Log every match, watch your home court
        light up on the map, and see the social rhythm of pickleball happening
        in real-time across the country.
      </p>
      <p className="text-base text-white/60 leading-relaxed">
        Most apps treat pickleball like a stat sheet. We treat it like a
        scene — green dots glow when courts are active, players see who's
        playing where, and games leave a trail behind them.
      </p>
      <div className="flex justify-end pt-2">
        <NextButton onClick={onNext}>Continue ▸</NextButton>
      </div>
    </div>
  );
}

function VouchSlide({
  onBack,
  onNext,
}: {
  onBack: () => void;
  onNext: () => void;
}) {
  return (
    <div className="space-y-4">
      <h2 className="font-display text-display-xl font-extrabold leading-tight text-bright">
        Honest stats start with vouching
      </h2>
      <p className="text-base text-white/80 leading-relaxed">
        After you finish a game, log the score. We notify your opponents — they
        confirm or dispute the result. Once an opponent vouches, the match goes
        official and your stats update on all four players' profiles.
      </p>
      <p className="text-base text-white/60 leading-relaxed">
        No vouch = no stats. It keeps leaderboards real, prevents
        sandbagging, and means every win in your record was earned — and
        someone signed off on it.
      </p>
      <div className="rounded-xl border-2 border-pickle/40 bg-pickle/5 p-4 text-sm text-white/70 leading-relaxed">
        <span className="font-display text-display-xs uppercase font-semibold tracking-wide text-pickle">
          Quick tip
        </span>
        <p className="mt-1.5">
          Played with non-members? Log them as guests — we'll send them an
          invite to claim the match (and their stats) when they join.
        </p>
      </div>
      <div className="flex items-center justify-between pt-2">
        <BackButton onClick={onBack} />
        <NextButton onClick={onNext}>Continue ▸</NextButton>
      </div>
    </div>
  );
}

function CompeteSlide({
  onBack,
  onNext,
}: {
  onBack: () => void;
  onNext: () => void;
}) {
  return (
    <div className="space-y-4">
      <h2 className="font-display text-display-xl font-extrabold leading-tight text-bright">
        Compete locally · Collect globally
      </h2>
      <p className="text-base text-white/80 leading-relaxed">
        See where you stand at four levels — at your home court, in your city,
        across your state, and nationally. Rankings refresh every match. Local
        rivalries finally have a scoreboard.
      </p>
      <div className="grid gap-3 sm:grid-cols-2">
        <div className="rounded-xl border-2 border-pickle/40 p-4">
          <div className="font-display text-display-xs uppercase font-semibold tracking-wide text-pickle">
            Monthly trophies
          </div>
          <p className="mt-1.5 text-sm text-white/70">
            Top 3 at every court each month win pixel-art trophies, themed
            uniquely for that month. Collected forever in your trophy room.
          </p>
        </div>
        <div className="rounded-xl border-2 border-electric/40 p-4">
          <div className="font-display text-display-xs uppercase font-semibold tracking-wide text-electric">
            Badges &amp; streaks
          </div>
          <p className="mt-1.5 text-sm text-white/70">
            Unlock badges for streaks, milestones, and rare feats. Your
            profile becomes a record of every chapter of your pickle journey.
          </p>
        </div>
      </div>
      <div className="flex items-center justify-between pt-2">
        <BackButton onClick={onBack} />
        <NextButton onClick={onNext}>Let&apos;s set you up ▸</NextButton>
      </div>
    </div>
  );
}

function FormStep({
  displayName,
  setDisplayName,
  dupr,
  setDupr,
  saving,
  error,
  onBack,
  onSubmit,
}: {
  displayName: string;
  setDisplayName: (s: string) => void;
  dupr: number;
  setDupr: (n: number) => void;
  saving: boolean;
  error: string | null;
  onBack: () => void;
  onSubmit: () => void;
}) {
  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        onSubmit();
      }}
      className="space-y-5"
    >
      <h2 className="font-display text-display-xl font-extrabold leading-tight text-bright">
        Tell us who you are
      </h2>
      <p className="text-base text-white/60">
        Two quick fields. You can add a profile picture, city, and more later
        from your profile.
      </p>

      <label className="block">
        <span className="font-display text-display-xs uppercase font-semibold tracking-wide text-pickle">
          Your name
        </span>
        <input
          type="text"
          value={displayName}
          onChange={(e) => setDisplayName(e.target.value)}
          required
          maxLength={40}
          autoFocus
          placeholder="First name or nickname"
          className="mt-2 block w-full rounded-lg border-2 border-white bg-black px-4 py-3 text-base text-white placeholder:text-white/40 focus:border-pickle focus:outline-none"
        />
      </label>

      <label className="block">
        <span className="font-display text-display-xs uppercase font-semibold tracking-wide text-pickle">
          Self-rating ({dupr.toFixed(1)})
        </span>
        <input
          type="range"
          min={2.0}
          max={8.0}
          step={0.5}
          value={dupr}
          onChange={(e) => setDupr(parseFloat(e.target.value))}
          className="mt-2 w-full accent-pickle"
        />
        <div className="mt-1 flex justify-between font-mono text-xs text-white/40">
          <span>2.0</span>
          <span>5.0</span>
          <span>8.0</span>
        </div>
        <p className="mt-2 text-xs text-white/50 leading-relaxed">
          DUPR-style: 2.0 = beginner, 3.0–4.0 = intermediate, 4.0–5.0 = advanced,
          5.0+ = elite.
        </p>
      </label>

      <div className="flex items-center justify-between gap-3 pt-2">
        <BackButton onClick={onBack} />
        <button
          type="submit"
          disabled={saving}
          className="soft-stamp rounded-xl bg-pickle px-6 py-3 font-display text-display-base font-extrabold uppercase tracking-wide text-black disabled:opacity-50"
        >
          {saving ? "Saving..." : "Let's play ▸"}
        </button>
      </div>

      {error && <p className="text-base text-bright">⚠ {error}</p>}
    </form>
  );
}

// ----- shared button atoms -----

function NextButton({
  onClick,
  children,
}: {
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="soft-stamp rounded-xl bg-pickle px-6 py-3 font-display text-display-base font-extrabold uppercase tracking-wide text-black"
    >
      {children}
    </button>
  );
}

function BackButton({ onClick }: { onClick: () => void }) {
  return (
    <button
      type="button"
      onClick={onClick}
      className="font-display text-display-xs uppercase font-semibold tracking-wide text-white/60 hover:text-pickle"
    >
      ◀ Back
    </button>
  );
}
